import json, os
from datetime import datetime, timezone
from topicparser import store, prefilter, ranker
from topicparser.cancellation import RunCancelled   # re-exported: api/tests import it from here
from topicparser import i18n


# How many already-shown titles are carried into a run. They ride inside EVERY scoring
# batch as well as the group and dedup calls, so an uncapped list makes a run cost more
# the older the database gets. 150 is several runs deep (the biggest run so far produced
# 49 topics) while the freshness window still decides what counts as recent at all.
RECENT_TITLES_CAP = 150


def _carry_title(recent_titles: list[str], title: str, cap: int = None) -> None:
    """Carry a title this run just produced into the list the NEXT profile dedups
    against, keeping the list capped and NEWEST-FIRST.

    `append` plus a re-slice looks like the obvious fix and does the opposite: the list
    comes back from `get_recent_topics` newest-first, so `[:cap]` keeps the oldest
    titles and throws away precisely the fresh ones this run was told to carry forward.
    New titles belong at the FRONT, and the tail is what falls off."""
    if cap is None:
        cap = RECENT_TITLES_CAP
    recent_titles.insert(0, title)
    del recent_titles[cap:]


def _scored_rows(signals, scored):
    """Map the LLM's per-signal scores back onto the signals, for the debug log."""
    rows = []
    by_i = {s["i"]: s for s in scored}
    for idx, sig in enumerate(signals):
        d = by_i.get(idx, {})
        # `date` is here because replay.load_signals reads it: without it every
        # replayed signal was rebuilt with an empty date, and no freshness question
        # (a feed publishing an unparseable pubDate, say) can be asked of the log.
        rows.append({"source": sig.source, "title": sig.title, "url": sig.url,
                     "text": sig.description, "date": sig.date,
                     "score": d.get("score"), "reason": d.get("reason", "")})
    return rows

def _write_debug(debug_dir, payload):
    os.makedirs(debug_dir, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    path = os.path.join(debug_dir, f"run-{stamp}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    return path

def _auto_track(topic, gh_by_url):
    """Every GitHub repo that reached a final topic is auto-added to the watchlist
    (the manual watch button is gone). A repo's canonical id is its signal title
    (== owner/repo, same key velocity uses). Record its first star snapshot now so
    velocity can compute one run sooner."""
    # description = the topic's `why` (already generated by the scorer, in the
    # interface language), so the watchlist reads like the feed; the English GitHub
    # blurb is the fallback.
    desc = topic.get("why") or None
    for link in topic.get("links", []):
        sig = gh_by_url.get(link)
        if sig is None:
            continue
        store.add_tracked_repo(sig.title, description=desc or sig.description)
        if sig.stars is not None:
            store.record_stars(sig.title, sig.stars)


# One place names a collector, for the progress line AND for the failure warning.
# Anything unknown used to fall through as the raw identifier, so the third source
# announced itself as "Collecting feed..." in a Ukrainian build and a failed fetch was
# labelled "feed".
_SRC_LABELS = {"github": "source.github", "x": "source.twitter", "feed": "kind.feeds"}


def _src_label(src):
    key = _SRC_LABELS.get(src)
    return i18n.t(key) if key else src


def run(*, selected, profiles, collectors, client, threshold, x_days, gh_days,
        feed_days=None, stagnant_days=21, min_velocity=50, batch_size=120, off_interest=None,
        prompt_loader=None, group_prompt_loader=None, dedup_prompt_loader=None,
        xgate_prompt_loader=None, feedgate_prompt_loader=None,
        debug_dir=None, cancel_event=None, progress=None):
    def _phase(msg):   # coarse status text for the UI; no-op when not wired
        if progress is not None:
            try:
                progress(msg)
            except Exception:
                pass
    if cancel_event is not None:
        for col in collectors:      # cooperative: collectors may check this mid-collect
            col.cancel_event = cancel_event
    warnings = []
    for col in collectors:
        # a collector that skips ONE bad source (a timed-out X account, a rate-limited
        # GitHub topic) reports it here instead of raising — the run keeps the rest of
        # its signals and the user still sees what was missed, in the red banner
        col.warn = warnings.append
    store.cleanup_topics(x_days=x_days, gh_days=gh_days, feed_days=feed_days)

    gh_col = next((c for c in collectors if getattr(c, "source", "") == "github"), None)
    if gh_col is not None and hasattr(gh_col, "measure_tracked"):
        try:
            gh_col.measure_tracked()
        except Exception as e:
            warnings.append(i18n.t("warn.stars_remeasure_failed", error=e))
    store.prune_star_history(days=store.STAR_HISTORY_DAYS)
    store.drop_stagnant_repos(days=stagnant_days)   # measure first (may reset growth), then cull

    # trending = SEPARATE channel, read straight off the watchlist (bypasses topic dedup)
    alerts = store.detect_trending(min_velocity=min_velocity)

    # the WIDEST window any source keeps, or a topic that survived cleanup is not in
    # the seen set and gets collected, scored and shown a second time
    window = max(x_days, gh_days, feed_days or gh_days)
    seen = store.seen_links(days=window)
    banned = store.get_banned_repos()
    recent_titles = [t["title"] for t in
                     store.get_recent_topics(days=window)
                     ][:RECENT_TITLES_CAP]        # newest first, so this keeps the newest

    all_topics = []
    # One stamp for the whole run, so every topic it writes can be found together
    # afterwards — that is what lets the feed come back after a restart.
    run_id = datetime.now(timezone.utc).isoformat()
    debug = {"time": run_id,
             "selected": selected, "threshold": threshold, "profiles": {}}

    written = []

    def _finish():
        """Everything the run owes the caller, whether it ran to the end, stopped, or
        died. The log is written ONCE (a `finally` plus an early return would write it
        twice) and it is written even on a crash: the one failure worth diagnosing was
        the one that produced no file at all."""
        if debug_dir and not written:
            written.append(_write_debug(debug_dir, debug))
        all_topics.sort(key=lambda t: t["score"], reverse=True)
        return {"topics": all_topics, "alerts": alerts, "warnings": warnings}

    try:
        _collect_and_score(selected, profiles, collectors, client, threshold,
                           x_days=x_days, gh_days=gh_days, feed_days=feed_days,
                           batch_size=batch_size,
                           off_interest=off_interest, prompt_loader=prompt_loader,
                           group_prompt_loader=group_prompt_loader,
                           dedup_prompt_loader=dedup_prompt_loader,
                           xgate_prompt_loader=xgate_prompt_loader,
                           feedgate_prompt_loader=feedgate_prompt_loader,
                           gh_col=gh_col, seen=seen, banned=banned,
                           recent_titles=recent_titles, warnings=warnings,
                           all_topics=all_topics, debug=debug, run_id=run_id,
                           cancel_event=cancel_event, phase=_phase)
    except RunCancelled:
        # Stop, not failure: hand back the profiles that DID finish. Their topics are
        # already in the DB and auto-tracked, so dropping them here would show the user
        # nothing while cross-run dedup silently buries the same stories next run.
        out = _finish()
        raise RunCancelled(topics=out["topics"], alerts=out["alerts"],
                           warnings=out["warnings"]) from None
    except Exception:
        _finish()          # keep the log; the caller still gets the exception
        raise

    return _finish()


def _collect_and_score(selected, profiles, collectors, client, threshold, *,
                       x_days, gh_days, feed_days, batch_size, off_interest, prompt_loader,
                       group_prompt_loader, dedup_prompt_loader, xgate_prompt_loader,
                       feedgate_prompt_loader,
                       gh_col, seen, banned, recent_titles, warnings, all_topics,
                       debug, run_id, cancel_event, phase):
    """One pass over the selected profiles, appending to `all_topics` / `debug` as it
    goes. Split out of `run` so a cancel anywhere inside it still leaves the caller
    holding everything gathered up to that point."""
    _phase = phase
    for name in selected:
        if cancel_event is not None and cancel_event.is_set():
            raise RunCancelled()
        cfg = profiles.get(name, {})
        signals = []
        x_sources = []
        for col in collectors:
            src = getattr(col, "source", "?")
            _phase(i18n.t("run.collecting", source=_src_label(src)))
            try:
                signals.extend(col.collect(name, cfg))
            except Exception as e:
                warnings.append(i18n.t("warn.source_failed", label=_src_label(src),
                                       profile=name, error=e))
            # what each X URL actually yielded, read the same loose way `warn` is
            # attached: it answers whether X_MAX_TWEETS or X_MAX_SCROLLS is binding
            x_sources.extend(getattr(col, "stats", None) or [])
        collected = len(signals)

        if cancel_event is not None and cancel_event.is_set():
            raise RunCancelled()

        if gh_col is not None and hasattr(gh_col, "attach_velocity"):
            signals = gh_col.attach_velocity(signals)
        signals = prefilter.filter_fresh(signals, gh_days=gh_days, x_days=x_days,
                                         feed_days=feed_days)
        signals = prefilter.drop_seen_links(signals, seen)
        signals = prefilter.drop_banned(signals, banned)
        # what the code filter removed, for the log: this cut runs BEFORE scoring, so
        # nothing downstream could ever report it and a term matching more than its
        # author meant left no trace at all
        off_dropped: list[str] = []
        signals = prefilter.drop_off_interest(signals, off_interest or set(),
                                              dropped=off_dropped.append)

        prof = {"collected": collected, "after_prefilter": len(signals),
                "scored": [], "topics": [], "raw": "",
                # here rather than beside the scored rows: a profile that scraped
                # almost nothing never reaches the scoring block, and that is exactly
                # when the per-URL numbers are worth having
                "x_sources": x_sources,
                # what each gate threw away — the log used to record scores and final
                # topics only, so a signal that scored 70 and produced no topic could
                # not be traced to the pass that removed it
                "dropped": {"off_interest": off_dropped,
                            "xgate": [], "feedgate": [], "dedup": []}}

        if signals:
            _phase(i18n.t("run.scoring"))
            system_prompt = prompt_loader(name) if prompt_loader else None
            group_prompt = (group_prompt_loader() or None) if group_prompt_loader else None
            dedup_prompt = (dedup_prompt_loader() or None) if dedup_prompt_loader else None
            xgate_prompt = (xgate_prompt_loader() or None) if xgate_prompt_loader else None
            feedgate_prompt = ((feedgate_prompt_loader() or None)
                               if feedgate_prompt_loader else None)
            # `keep` is the SAME bar the filter below applies. It used to be left at
            # the ranker's own default of 70, so a threshold under 70 was a knob wired
            # to nothing: everything below 70 had already been dropped before the
            # filter ever saw it.
            # An empty prompt file and NO prompt loader are the same disaster: the
            # ranker falls back to its 14-line DEFAULT_SYSTEM, every tuned rule
            # disappears, both gates are skipped, and the run still produces a full,
            # plausible feed. Measured on 2026-08-22 with the loaders left unwired:
            # 809 topics against the usual 20-49, 274 signals exactly on 70, both
            # gates dropping nothing, every reason in English. The flag comes back
            # from `rank`, so the check cannot drift away from what was really used.
            result = ranker.rank(signals, recent_titles, client, system_prompt,
                                  batch_size=batch_size, keep=threshold,
                                  group_prompt=group_prompt,
                                  dedup_prompt=dedup_prompt, xgate_prompt=xgate_prompt,
                                  feedgate_prompt=feedgate_prompt,
                                  cancel_event=cancel_event)
            if result.get("no_prompt"):
                warnings.append(i18n.t("warn.prompt_missing", profile=name))
            # The most expensive call in the run was also the only silent one. A
            # swallowed batch keeps the run alive; saying nothing about it lets a dead
            # key or a rate limit arrive as "0 topics", which reads as a quiet news day
            # after fifteen minutes of scraping.
            if result.get("failed_batches"):
                warnings.append(i18n.t("warn.score_batches_failed",
                                       count=result["failed_batches"]))
            elif signals and not result["scored"]:
                warnings.append(i18n.t("warn.nothing_scored"))
            else:
                # The third silent shape, and the only one the user can cause: the bar
                # is above what the model ever gives. `SCORE_THRESHOLD` goes to 100
                # from the Settings screen, while over 3430 signals nothing has scored
                # past 90. Neither branch above sees it — no batch failed, `scored` is
                # full — so the feed said "0 topics" with no warning after twelve minutes
                # of scraping. Only when the BAR is what stopped them: a signal that
                # cleared it and was then dropped by a gate is a different story, and
                # naming the threshold there would send the reader after the wrong knob.
                best = max((s.get("score") or 0 for s in result["scored"]), default=0)
                if best < threshold:
                    warnings.append(i18n.t("warn.nothing_passed",
                                           threshold=threshold, best=best))
            topics = [t for t in result["topics"] if t["score"] >= threshold]
            topics.sort(key=lambda t: t["score"], reverse=True)
            gh_by_url = {s.url: s for s in signals if s.source == "github"}
            for t in topics:
                t["id"] = store.insert_topic(
                    title=t["title"], why=t["why"], links=t["links"],
                    signature=t["title"].lower(), score=t["score"], profile=name,
                    source=t.get("source"), run_id=run_id)
                _auto_track(t, gh_by_url)
                # Carry this profile's result into the NEXT profile's filters. Both
                # were read once, before the loop, so a source two profiles share
                # (an X list, a GitHub topic) was scored twice and shown twice.
                # `seen` stops it before the paid call; `recent_titles` catches the
                # same story arriving under a different link.
                seen.update(t["links"])
                # front, not back: the list is newest-first and capped, and appending
                # to it left the cap applying to the DB half only — a second profile
                # then carried `cap + everything the first profile produced` inside
                # every scoring batch, which is the cost the cap exists to bound
                _carry_title(recent_titles, t["title"])
            all_topics.extend(topics)
            prof["scored"] = _scored_rows(signals, result["scored"])
            prof["topics"] = topics
            prof["raw"] = result["raw"]
            # the ranker owns the three gate keys; `off_interest` happened before it
            prof["dropped"] = {**result.get("dropped", {}),
                               "off_interest": off_dropped}
            # Both end as a null score in `scored`; the PAIR says why without a grep.
            # `unscored` counts every signal left without a score, dead batches
            # included, so: both non-zero = calls were failing, `unscored` alone = a
            # reply that parsed and left signals out.
            prof["failed_batches"] = result.get("failed_batches", 0)
            prof["unscored"] = result.get("unscored", 0)

        debug["profiles"][name] = prof
